
# ai_serp_auditor.py - Auto-generated by quick_install.py
"""AI-SERP Self-Auditor - Standalone Package"""

import os
import json
import logging
import hashlib
from datetime import datetime
from typing import Dict, List, Any, Optional
from dataclasses import dataclass
from enum import Enum

import requests
from bs4 import BeautifulSoup
from openai import OpenAI

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class AutoFixMode(Enum):
    OFF = "off"
    PROPOSE = "propose"
    AUTO = "auto"

@dataclass
class AuditConfig:
    site_url: str
    brand_name: str
    focus_keywords: List[str] = None
    auto_fix_mode: AutoFixMode = AutoFixMode.PROPOSE
    
    def __post_init__(self):
        if self.focus_keywords is None:
            self.focus_keywords = []

class AIAnalyzer:
    def __init__(self, api_key: str = None, base_url: str = None):
        self.api_key = api_key or os.environ.get("OPENAI_API_KEY") or os.environ.get("AI_INTEGRATIONS_OPENAI_API_KEY")
        self.base_url = base_url or os.environ.get("AI_INTEGRATIONS_OPENAI_BASE_URL")
        if not self.api_key:
            raise ValueError("OpenAI API key not found. Set OPENAI_API_KEY in Replit Secrets.")
        self.client = OpenAI(api_key=self.api_key, base_url=self.base_url)
    
    def analyze_page(self, url: str, content: str, brand_name: str) -> Dict[str, Any]:
        try:
            prompt = f"""Analyze this webpage for AI search visibility.
URL: {url}
Brand: {brand_name}
Content: {content[:8000]}

Respond with JSON:
{{"visibility_score": 0-100, "seo_score": 0-100, "ai_context_score": 0-100, "authority_score": 0-100,
"quick_wins": [{{"priority": 1-10, "action": "description", "impact": "HIGH/MEDIUM/LOW"}}],
"technical_issues": ["issue1"], "schema_recommendations": ["rec1"]}}"""

            response = self.client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "system", "content": "AI search optimization expert. Respond only with JSON."},
                          {"role": "user", "content": prompt}],
                max_tokens=2000, temperature=0.3)
            
            result_text = response.choices[0].message.content.strip()
            if result_text.startswith("```"):
                result_text = result_text.split("```")[1].lstrip("json")
            return json.loads(result_text)
        except Exception as e:
            logger.error(f"AI analysis failed: {e}")
            return {"visibility_score": 50, "seo_score": 50, "ai_context_score": 50, "authority_score": 50,
                    "quick_wins": [], "technical_issues": [str(e)], "schema_recommendations": []}

class WebCrawler:
    def __init__(self):
        self.session = requests.Session()
        self.session.headers.update({"User-Agent": "AI-SERP-Auditor/1.0"})
    
    def crawl(self, url: str) -> Dict[str, Any]:
        try:
            response = self.session.get(url, timeout=30)
            response.raise_for_status()
            soup = BeautifulSoup(response.text, "html.parser")
            
            title = soup.find("title")
            meta_desc = soup.find("meta", attrs={"name": "description"})
            
            for tag in soup(["script", "style", "nav", "footer"]):
                tag.decompose()
            text = soup.get_text(separator=" ", strip=True)
            
            return {"url": url, "title": title.get_text(strip=True) if title else "",
                    "meta_description": meta_desc.get("content", "") if meta_desc else "",
                    "text_content": text[:15000], "word_count": len(text.split())}
        except Exception as e:
            return {"url": url, "error": str(e)}

class SelfAuditor:
    def __init__(self, config: AuditConfig, db_path: str = "audit_data.json"):
        self.config = config
        self.db_path = db_path
        self.crawler = WebCrawler()
        self.analyzer = AIAnalyzer()
        self.data = self._load_data()
    
    def _load_data(self) -> Dict:
        if os.path.exists(self.db_path):
            with open(self.db_path, "r") as f:
                return json.load(f)
        return {"audits": [], "fixes": [], "config": {}}
    
    def _save_data(self):
        with open(self.db_path, "w") as f:
            json.dump(self.data, f, indent=2, default=str)
    
    def run_audit(self) -> Dict[str, Any]:
        logger.info(f"Starting audit for {self.config.site_url}")
        audit_id = f"audit_{datetime.now().strftime(\"%Y%m%d_%H%M%S\")}"
        
        crawl_data = self.crawler.crawl(self.config.site_url)
        if "error" in crawl_data:
            return {"audit_id": audit_id, "success": False, "error": crawl_data["error"]}
        
        analysis = self.analyzer.analyze_page(self.config.site_url, crawl_data.get("text_content", ""), self.config.brand_name)
        fixes = self._extract_fixes(analysis)
        
        audit_result = {
            "audit_id": audit_id, "success": True, "site_url": self.config.site_url,
            "brand_name": self.config.brand_name, "timestamp": datetime.now().isoformat(),
            "scores": {"visibility": analysis.get("visibility_score", 0), "seo": analysis.get("seo_score", 0),
                       "ai_context": analysis.get("ai_context_score", 0), "authority": analysis.get("authority_score", 0)},
            "fixes_count": len(fixes), "fixes": fixes}
        
        self.data["audits"].append(audit_result)
        for fix in fixes:
            fix["audit_id"] = audit_id
            fix["status"] = "pending"
            self.data["fixes"].append(fix)
        self._save_data()
        return audit_result
    
    def _extract_fixes(self, analysis: Dict) -> List[Dict]:
        fixes = []
        for i, win in enumerate(analysis.get("quick_wins", []), 1):
            fixes.append({"id": f"qw_{i}", "category": "quick_win", "priority": win.get("priority", 5),
                          "action": win.get("action", ""), "impact": win.get("impact", "MEDIUM"), "auto_fixable": False})
        for i, issue in enumerate(analysis.get("technical_issues", []), 1):
            fixes.append({"id": f"tech_{i}", "category": "technical", "priority": 3,
                          "action": f"Fix: {issue}", "impact": "HIGH", "auto_fixable": False})
        return fixes
    
    def get_pending_fixes(self) -> List[Dict]:
        return [f for f in self.data.get("fixes", []) if f.get("status") == "pending"]
    
    def get_audit_history(self) -> List[Dict]:
        return sorted(self.data.get("audits", []), key=lambda x: x.get("timestamp", ""), reverse=True)
    
    def apply_fix(self, fix_id: str) -> bool:
        for fix in self.data.get("fixes", []):
            if fix.get("id") == fix_id:
                fix["status"] = "applied"
                fix["applied_at"] = datetime.now().isoformat()
                self._save_data()
                return True
        return False
    
    def reject_fix(self, fix_id: str) -> bool:
        for fix in self.data.get("fixes", []):
            if fix.get("id") == fix_id:
                fix["status"] = "rejected"
                self._save_data()
                return True
        return False

class AgenticUpdater:
    def __init__(self, db_path: str = "signals_data.json"):
        self.db_path = db_path
        api_key = os.environ.get("OPENAI_API_KEY") or os.environ.get("AI_INTEGRATIONS_OPENAI_API_KEY")
        if api_key:
            self.client = OpenAI(api_key=api_key, base_url=os.environ.get("AI_INTEGRATIONS_OPENAI_BASE_URL"))
        else:
            self.client = None
        self.data = self._load_data()
    
    def _load_data(self) -> Dict:
        if os.path.exists(self.db_path):
            with open(self.db_path, "r") as f:
                return json.load(f)
        return {"signals": self._get_default_signals(), "updates": []}
    
    def _save_data(self):
        with open(self.db_path, "w") as f:
            json.dump(self.data, f, indent=2, default=str)
    
    def _get_default_signals(self) -> List[Dict]:
        return [
            {"id": "1", "name": "Entity Clarity", "category": "E-E-A-T", "weight": 9},
            {"id": "2", "name": "Author Expertise", "category": "E-E-A-T", "weight": 8},
            {"id": "3", "name": "Content Freshness", "category": "Content", "weight": 7},
            {"id": "4", "name": "Schema Markup", "category": "Technical", "weight": 8},
            {"id": "5", "name": "LLM Readability", "category": "Content", "weight": 9},
            {"id": "6", "name": "Citation Quality", "category": "Authority", "weight": 7},
            {"id": "7", "name": "Topical Authority", "category": "Authority", "weight": 8}]
    
    def get_signals(self) -> List[Dict]:
        return self.data.get("signals", [])
    
    def get_update_history(self) -> List[Dict]:
        return sorted(self.data.get("updates", []), key=lambda x: x.get("timestamp", ""), reverse=True)
