#!/usr/bin/env python3
"""
AI-SERP Auditor - Quick Install Script
Run this single file to install the complete package on any Replit project.

Usage:
  1. Copy this file to your Replit project
  2. Run: python quick_install.py
  3. Add your secrets (OPENAI_API_KEY, SITE_URL, BRAND_NAME)
  4. Run: python dashboard.py
"""

import os
import sys
import subprocess

print("=" * 60)
print("AI-SERP Auditor - Quick Install")
print("=" * 60)

print("\nInstalling dependencies...")
subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", 
    "openai", "requests", "beautifulsoup4", "flask"])
print("Dependencies installed!")

AUDITOR_CODE = '''
# ai_serp_auditor.py - Auto-generated by quick_install.py
"""AI-SERP Self-Auditor - Standalone Package"""

import os
import json
import logging
import hashlib
from datetime import datetime
from typing import Dict, List, Any, Optional
from dataclasses import dataclass
from enum import Enum

import requests
from bs4 import BeautifulSoup
from openai import OpenAI

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class AutoFixMode(Enum):
    OFF = "off"
    PROPOSE = "propose"
    AUTO = "auto"

@dataclass
class AuditConfig:
    site_url: str
    brand_name: str
    focus_keywords: List[str] = None
    auto_fix_mode: AutoFixMode = AutoFixMode.PROPOSE
    
    def __post_init__(self):
        if self.focus_keywords is None:
            self.focus_keywords = []

class AIAnalyzer:
    def __init__(self, api_key: str = None, base_url: str = None):
        self.api_key = api_key or os.environ.get("OPENAI_API_KEY") or os.environ.get("AI_INTEGRATIONS_OPENAI_API_KEY")
        self.base_url = base_url or os.environ.get("AI_INTEGRATIONS_OPENAI_BASE_URL")
        if not self.api_key:
            raise ValueError("OpenAI API key not found. Set OPENAI_API_KEY in Replit Secrets.")
        self.client = OpenAI(api_key=self.api_key, base_url=self.base_url)
    
    def analyze_page(self, url: str, content: str, brand_name: str) -> Dict[str, Any]:
        try:
            prompt = f"""Analyze this webpage for AI search visibility.
URL: {url}
Brand: {brand_name}
Content: {content[:8000]}

Respond with JSON:
{{"visibility_score": 0-100, "seo_score": 0-100, "ai_context_score": 0-100, "authority_score": 0-100,
"quick_wins": [{{"priority": 1-10, "action": "description", "impact": "HIGH/MEDIUM/LOW"}}],
"technical_issues": ["issue1"], "schema_recommendations": ["rec1"]}}"""

            response = self.client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "system", "content": "AI search optimization expert. Respond only with JSON."},
                          {"role": "user", "content": prompt}],
                max_tokens=2000, temperature=0.3)
            
            result_text = response.choices[0].message.content.strip()
            if result_text.startswith("```"):
                result_text = result_text.split("```")[1].lstrip("json")
            return json.loads(result_text)
        except Exception as e:
            logger.error(f"AI analysis failed: {e}")
            return {"visibility_score": 50, "seo_score": 50, "ai_context_score": 50, "authority_score": 50,
                    "quick_wins": [], "technical_issues": [str(e)], "schema_recommendations": []}

class WebCrawler:
    def __init__(self):
        self.session = requests.Session()
        self.session.headers.update({"User-Agent": "AI-SERP-Auditor/1.0"})
    
    def crawl(self, url: str) -> Dict[str, Any]:
        try:
            response = self.session.get(url, timeout=30)
            response.raise_for_status()
            soup = BeautifulSoup(response.text, "html.parser")
            
            title = soup.find("title")
            meta_desc = soup.find("meta", attrs={"name": "description"})
            
            for tag in soup(["script", "style", "nav", "footer"]):
                tag.decompose()
            text = soup.get_text(separator=" ", strip=True)
            
            return {"url": url, "title": title.get_text(strip=True) if title else "",
                    "meta_description": meta_desc.get("content", "") if meta_desc else "",
                    "text_content": text[:15000], "word_count": len(text.split())}
        except Exception as e:
            return {"url": url, "error": str(e)}

class SelfAuditor:
    def __init__(self, config: AuditConfig, db_path: str = "audit_data.json"):
        self.config = config
        self.db_path = db_path
        self.crawler = WebCrawler()
        self.analyzer = AIAnalyzer()
        self.data = self._load_data()
    
    def _load_data(self) -> Dict:
        if os.path.exists(self.db_path):
            with open(self.db_path, "r") as f:
                return json.load(f)
        return {"audits": [], "fixes": [], "config": {}}
    
    def _save_data(self):
        with open(self.db_path, "w") as f:
            json.dump(self.data, f, indent=2, default=str)
    
    def run_audit(self) -> Dict[str, Any]:
        logger.info(f"Starting audit for {self.config.site_url}")
        audit_id = f"audit_{datetime.now().strftime(\\"%Y%m%d_%H%M%S\\")}"
        
        crawl_data = self.crawler.crawl(self.config.site_url)
        if "error" in crawl_data:
            return {"audit_id": audit_id, "success": False, "error": crawl_data["error"]}
        
        analysis = self.analyzer.analyze_page(self.config.site_url, crawl_data.get("text_content", ""), self.config.brand_name)
        fixes = self._extract_fixes(analysis)
        
        audit_result = {
            "audit_id": audit_id, "success": True, "site_url": self.config.site_url,
            "brand_name": self.config.brand_name, "timestamp": datetime.now().isoformat(),
            "scores": {"visibility": analysis.get("visibility_score", 0), "seo": analysis.get("seo_score", 0),
                       "ai_context": analysis.get("ai_context_score", 0), "authority": analysis.get("authority_score", 0)},
            "fixes_count": len(fixes), "fixes": fixes}
        
        self.data["audits"].append(audit_result)
        for fix in fixes:
            fix["audit_id"] = audit_id
            fix["status"] = "pending"
            self.data["fixes"].append(fix)
        self._save_data()
        return audit_result
    
    def _extract_fixes(self, analysis: Dict) -> List[Dict]:
        fixes = []
        for i, win in enumerate(analysis.get("quick_wins", []), 1):
            fixes.append({"id": f"qw_{i}", "category": "quick_win", "priority": win.get("priority", 5),
                          "action": win.get("action", ""), "impact": win.get("impact", "MEDIUM"), "auto_fixable": False})
        for i, issue in enumerate(analysis.get("technical_issues", []), 1):
            fixes.append({"id": f"tech_{i}", "category": "technical", "priority": 3,
                          "action": f"Fix: {issue}", "impact": "HIGH", "auto_fixable": False})
        return fixes
    
    def get_pending_fixes(self) -> List[Dict]:
        return [f for f in self.data.get("fixes", []) if f.get("status") == "pending"]
    
    def get_audit_history(self) -> List[Dict]:
        return sorted(self.data.get("audits", []), key=lambda x: x.get("timestamp", ""), reverse=True)
    
    def apply_fix(self, fix_id: str) -> bool:
        for fix in self.data.get("fixes", []):
            if fix.get("id") == fix_id:
                fix["status"] = "applied"
                fix["applied_at"] = datetime.now().isoformat()
                self._save_data()
                return True
        return False
    
    def reject_fix(self, fix_id: str) -> bool:
        for fix in self.data.get("fixes", []):
            if fix.get("id") == fix_id:
                fix["status"] = "rejected"
                self._save_data()
                return True
        return False

class AgenticUpdater:
    def __init__(self, db_path: str = "signals_data.json"):
        self.db_path = db_path
        api_key = os.environ.get("OPENAI_API_KEY") or os.environ.get("AI_INTEGRATIONS_OPENAI_API_KEY")
        if api_key:
            self.client = OpenAI(api_key=api_key, base_url=os.environ.get("AI_INTEGRATIONS_OPENAI_BASE_URL"))
        else:
            self.client = None
        self.data = self._load_data()
    
    def _load_data(self) -> Dict:
        if os.path.exists(self.db_path):
            with open(self.db_path, "r") as f:
                return json.load(f)
        return {"signals": self._get_default_signals(), "updates": []}
    
    def _save_data(self):
        with open(self.db_path, "w") as f:
            json.dump(self.data, f, indent=2, default=str)
    
    def _get_default_signals(self) -> List[Dict]:
        return [
            {"id": "1", "name": "Entity Clarity", "category": "E-E-A-T", "weight": 9},
            {"id": "2", "name": "Author Expertise", "category": "E-E-A-T", "weight": 8},
            {"id": "3", "name": "Content Freshness", "category": "Content", "weight": 7},
            {"id": "4", "name": "Schema Markup", "category": "Technical", "weight": 8},
            {"id": "5", "name": "LLM Readability", "category": "Content", "weight": 9},
            {"id": "6", "name": "Citation Quality", "category": "Authority", "weight": 7},
            {"id": "7", "name": "Topical Authority", "category": "Authority", "weight": 8}]
    
    def get_signals(self) -> List[Dict]:
        return self.data.get("signals", [])
    
    def get_update_history(self) -> List[Dict]:
        return sorted(self.data.get("updates", []), key=lambda x: x.get("timestamp", ""), reverse=True)
'''

DASHBOARD_CODE = '''
# dashboard.py - Auto-generated by quick_install.py
"""AI-SERP Auditor - Web Dashboard"""

import os
import json
from flask import Flask, render_template_string, request, redirect, url_for
from ai_serp_auditor import AuditConfig, SelfAuditor, AgenticUpdater, AutoFixMode

app = Flask(__name__)

DASHBOARD_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI-SERP Auditor</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: -apple-system, sans-serif; background: #0f172a; color: #e2e8f0; min-height: 100vh; }
        .container { max-width: 1200px; margin: 0 auto; padding: 2rem; }
        h1 { color: #f8fafc; margin-bottom: 2rem; }
        .card { background: #1e293b; border-radius: 12px; padding: 1.5rem; margin-bottom: 1.5rem; }
        .card-title { color: #f8fafc; margin-bottom: 1rem; font-size: 1.25rem; }
        .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; }
        .score-card { background: #0f172a; border-radius: 8px; padding: 1rem; text-align: center; }
        .score-value { font-size: 2.5rem; font-weight: bold; }
        .score-label { color: #94a3b8; font-size: 0.875rem; }
        .score-green { color: #4ade80; }
        .score-yellow { color: #fbbf24; }
        .score-red { color: #f87171; }
        .btn { display: inline-block; padding: 0.75rem 1.5rem; border-radius: 8px; border: none; cursor: pointer; font-size: 1rem; }
        .btn-primary { background: linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%); color: white; }
        .btn-success { background: #065f46; color: white; }
        .btn-danger { background: #7f1d1d; color: white; }
        .fix-item { background: #0f172a; border-radius: 8px; padding: 1rem; margin-bottom: 0.75rem; border-left: 3px solid #3b82f6; }
        .fix-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.5rem; }
        .badge { display: inline-block; padding: 0.25rem 0.5rem; border-radius: 4px; font-size: 0.75rem; margin-right: 0.5rem; background: #4ade8022; color: #4ade80; }
        .config-form input, .config-form select { width: 100%; padding: 0.75rem; margin-bottom: 1rem; border-radius: 8px; border: 1px solid #334155; background: #0f172a; color: #e2e8f0; }
        .config-form label { display: block; margin-bottom: 0.5rem; color: #94a3b8; }
        .status { padding: 1rem; border-radius: 8px; margin-bottom: 1rem; }
        .status-success { background: #065f4622; border: 1px solid #065f46; }
        .status-error { background: #7f1d1d22; border: 1px solid #7f1d1d; }
        .btn-group { display: flex; gap: 0.5rem; }
        .btn-sm { padding: 0.5rem 1rem; font-size: 0.875rem; }
    </style>
</head>
<body>
    <div class="container">
        <h1>AI-SERP Auditor Dashboard</h1>
        {% if message %}
        <div class="status {{ 'status-success' if success else 'status-error' }}">{{ message }}</div>
        {% endif %}
        
        <div class="card">
            <h2 class="card-title">Configuration</h2>
            <form class="config-form" method="POST" action="/config">
                <div class="grid">
                    <div><label>Site URL</label><input type="url" name="site_url" value="{{ config.site_url }}" required></div>
                    <div><label>Brand Name</label><input type="text" name="brand_name" value="{{ config.brand_name }}" required></div>
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
        
        <div class="card">
            <h2 class="card-title">Actions</h2>
            <form method="POST" action="/audit" style="display: inline;"><button class="btn btn-primary">Run Self-Audit</button></form>
        </div>
        
        {% if latest_audit %}
        <div class="card">
            <h2 class="card-title">Latest Scores</h2>
            <div class="grid">
                <div class="score-card"><div class="score-value {{ 'score-green' if latest_audit.scores.visibility >= 80 else 'score-yellow' if latest_audit.scores.visibility >= 60 else 'score-red' }}">{{ latest_audit.scores.visibility }}</div><div class="score-label">Visibility</div></div>
                <div class="score-card"><div class="score-value {{ 'score-green' if latest_audit.scores.seo >= 80 else 'score-yellow' if latest_audit.scores.seo >= 60 else 'score-red' }}">{{ latest_audit.scores.seo }}</div><div class="score-label">SEO</div></div>
                <div class="score-card"><div class="score-value {{ 'score-green' if latest_audit.scores.ai_context >= 80 else 'score-yellow' if latest_audit.scores.ai_context >= 60 else 'score-red' }}">{{ latest_audit.scores.ai_context }}</div><div class="score-label">AI Context</div></div>
                <div class="score-card"><div class="score-value {{ 'score-green' if latest_audit.scores.authority >= 80 else 'score-yellow' if latest_audit.scores.authority >= 60 else 'score-red' }}">{{ latest_audit.scores.authority }}</div><div class="score-label">Authority</div></div>
            </div>
        </div>
        {% endif %}
        
        <div class="card">
            <h2 class="card-title">Pending Fixes ({{ pending_fixes|length }})</h2>
            {% for fix in pending_fixes %}
            <div class="fix-item">
                <div class="fix-header">
                    <div><span class="badge">{{ fix.category }}</span> {{ fix.action }}</div>
                    <div class="btn-group">
                        <form method="POST" action="/fix/{{ fix.id }}/apply"><button class="btn btn-success btn-sm">Apply</button></form>
                        <form method="POST" action="/fix/{{ fix.id }}/reject"><button class="btn btn-danger btn-sm">Reject</button></form>
                    </div>
                </div>
            </div>
            {% else %}
            <p style="color: #94a3b8;">No pending fixes.</p>
            {% endfor %}
        </div>
    </div>
</body>
</html>"""

CONFIG_FILE = "config.json"

def load_config():
    if os.path.exists(CONFIG_FILE):
        with open(CONFIG_FILE, "r") as f:
            return json.load(f)
    return {"site_url": os.environ.get("SITE_URL", ""), "brand_name": os.environ.get("BRAND_NAME", "")}

def save_config_file(config):
    with open(CONFIG_FILE, "w") as f:
        json.dump(config, f, indent=2)

config_data = load_config()

def get_auditor():
    return SelfAuditor(AuditConfig(site_url=config_data["site_url"], brand_name=config_data["brand_name"]))

@app.route("/")
def index():
    auditor = get_auditor()
    history = auditor.get_audit_history()
    return render_template_string(DASHBOARD_HTML, config=config_data, latest_audit=history[0] if history else None,
                                  pending_fixes=auditor.get_pending_fixes(), message=request.args.get("message"),
                                  success=request.args.get("success") == "true")

@app.route("/config", methods=["POST"])
def update_config():
    global config_data
    config_data["site_url"] = request.form.get("site_url", "")
    config_data["brand_name"] = request.form.get("brand_name", "")
    save_config_file(config_data)
    return redirect("/?message=Configuration+saved!&success=true")

@app.route("/audit", methods=["POST"])
def run_audit():
    if not config_data["site_url"]:
        return redirect("/?message=Configure+site+URL+first&success=false")
    result = get_auditor().run_audit()
    if result.get("success"):
        return redirect(f"/?message=Audit+complete!+Score:+{result['scores']['visibility']}/100&success=true")
    return redirect(f"/?message=Audit+failed:+{result.get('error')}&success=false")

@app.route("/fix/<fix_id>/apply", methods=["POST"])
def apply_fix(fix_id):
    if get_auditor().apply_fix(fix_id):
        return redirect(f"/?message=Fix+{fix_id}+marked+as+applied&success=true")
    return redirect(f"/?message=Failed+to+apply+fix&success=false")

@app.route("/fix/<fix_id>/reject", methods=["POST"])
def reject_fix(fix_id):
    if get_auditor().reject_fix(fix_id):
        return redirect(f"/?message=Fix+{fix_id}+rejected&success=true")
    return redirect(f"/?message=Failed+to+reject+fix&success=false")

if __name__ == "__main__":
    print("Starting AI-SERP Auditor Dashboard on port 5000...")
    app.run(host="0.0.0.0", port=5000, debug=True)
'''

print("\nCreating ai_serp_auditor.py...")
with open("ai_serp_auditor.py", "w") as f:
    f.write(AUDITOR_CODE)

print("Creating dashboard.py...")
with open("dashboard.py", "w") as f:
    f.write(DASHBOARD_CODE)

print("\n" + "=" * 60)
print("INSTALLATION COMPLETE!")
print("=" * 60)
print("""
Next steps:

1. Add your secrets in Replit Secrets (Tools > Secrets):
   - OPENAI_API_KEY: Your OpenAI API key
   - SITE_URL: Website URL to audit (optional, can set in dashboard)
   - BRAND_NAME: Your brand name (optional)

2. Start the dashboard:
   python dashboard.py

3. Open your Repl's URL to access the dashboard

The dashboard lets you:
- Configure your site URL and brand name
- Run self-audits to analyze AI search visibility
- View and manage recommended fixes
- Track audit history and scores

Note: Fixes are tracked for manual implementation. 
The tool identifies issues but you apply changes to your site.
""")
